"""add complaint  status

Revision ID: d1d35b0f26f8
Revises: 554849ae27de
Create Date: 2026-09-26 13:17:53.711057

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd1d35b0f26f8'
down_revision = '554849ae27de'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('complaint', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.Enum('sent', 'pending', 'approved', 'solved', name='complaintstatus'), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('complaint', schema=None) as batch_op:
        batch_op.drop_column('status')

    # ### end Alembic commands ###
